[2024-12-17T03:03:20.702+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-17T03:03:14.728338+00:00 [queued]>
[2024-12-17T03:03:20.708+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-17T03:03:14.728338+00:00 [queued]>
[2024-12-17T03:03:20.708+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-17T03:03:20.715+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): arsenal_etl_group.etl_arsenal_task> on 2024-12-17 03:03:14.728338+00:00
[2024-12-17T03:03:20.720+0000] {standard_task_runner.py:57} INFO - Started process 80413 to run task
[2024-12-17T03:03:20.723+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'arsenal_mancity_etl', 'arsenal_etl_group.etl_arsenal_task', 'manual__2024-12-17T03:03:14.728338+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/arsenal_mancity_etl.py', '--cfg-path', '/tmp/tmpdyuhs1pn']
[2024-12-17T03:03:20.724+0000] {standard_task_runner.py:85} INFO - Job 323: Subtask arsenal_etl_group.etl_arsenal_task
[2024-12-17T03:03:20.777+0000] {task_command.py:410} INFO - Running <TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-17T03:03:14.728338+00:00 [running]> on host 653f470dc9b4
[2024-12-17T03:03:20.861+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='arsenal_mancity_etl' AIRFLOW_CTX_TASK_ID='arsenal_etl_group.etl_arsenal_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-17T03:03:14.728338+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-17T03:03:14.728338+00:00'
[2024-12-17T03:03:21.125+0000] {logging_mixin.py:149} INFO - Processing file: ben_white_match_logs_2023_2024.json
[2024-12-17T03:03:21.125+0000] {logging_mixin.py:149} INFO - Columns in DataFrame: ['', 'header_performance', 'header_expected', 'header_sca', 'header_passes', 'header_carries', 'header_take_ons', 'date', 'dayofweek', 'comp', 'round', 'venue', 'result', 'team', 'opponent', 'game_started', 'position', 'minutes', 'goals', 'assists', 'pens_made', 'pens_att', 'shots', 'shots_on_target', 'cards_yellow', 'cards_red', 'touches', 'tackles', 'interceptions', 'blocks', 'xg', 'npxg', 'xg_assist', 'sca', 'gca', 'passes_completed', 'passes', 'passes_pct', 'progressive_passes', 'carries', 'progressive_carries', 'take_ons', 'take_ons_won', 'match_report']
[2024-12-17T03:03:21.126+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/arsenal_mancity_etl.py", line 97, in etl_arsenal
    matches, player_stats, gk_stats = transform_data(player_name, df)
  File "/opt/airflow/dags/arsenal_mancity_etl.py", line 66, in transform_data
    matches = df[['match_id', 'date', 'opponent', 'venue', 'result', 'goals_scored', 'goals_conceded']].drop_duplicates()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['match_id', 'goals_scored', 'goals_conceded'] not in index"
[2024-12-17T03:03:21.137+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=arsenal_mancity_etl, task_id=arsenal_etl_group.etl_arsenal_task, execution_date=20241217T030314, start_date=20241217T030320, end_date=20241217T030321
[2024-12-17T03:03:21.145+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 323 for task arsenal_etl_group.etl_arsenal_task ("['match_id', 'goals_scored', 'goals_conceded'] not in index"; 80413)
[2024-12-17T03:03:21.159+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-17T03:03:21.188+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
