[2024-12-13T07:00:04.150+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres_etl.extract_data manual__2024-12-13T06:56:26.203594+00:00 [queued]>
[2024-12-13T07:00:04.154+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres_etl.extract_data manual__2024-12-13T06:56:26.203594+00:00 [queued]>
[2024-12-13T07:00:04.154+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-13T07:00:04.159+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data> on 2024-12-13 06:56:26.203594+00:00
[2024-12-13T07:00:04.163+0000] {standard_task_runner.py:57} INFO - Started process 427 to run task
[2024-12-13T07:00:04.166+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres_etl', 'extract_data', 'manual__2024-12-13T06:56:26.203594+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres_etl.py', '--cfg-path', '/tmp/tmpq1qp8f0_']
[2024-12-13T07:00:04.168+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask extract_data
[2024-12-13T07:00:04.202+0000] {task_command.py:410} INFO - Running <TaskInstance: minio_to_postgres_etl.extract_data manual__2024-12-13T06:56:26.203594+00:00 [running]> on host cfca890b9e35
[2024-12-13T07:00:04.387+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres_etl' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T06:56:26.203594+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T06:56:26.203594+00:00'
[2024-12-13T07:00:05.899+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-13T07:00:06.235+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 427. PIDs of all processes in the group: [427]
[2024-12-13T07:00:06.255+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 427
[2024-12-13T07:00:06.260+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
