[2024-12-13T14:51:23.619+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mancity_to_postgres_etl.etl_erling_halaand_logs manual__2024-12-13T14:51:21.223048+00:00 [queued]>
[2024-12-13T14:51:23.623+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mancity_to_postgres_etl.etl_erling_halaand_logs manual__2024-12-13T14:51:21.223048+00:00 [queued]>
[2024-12-13T14:51:23.624+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-13T14:51:23.630+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_erling_halaand_logs> on 2024-12-13 14:51:21.223048+00:00
[2024-12-13T14:51:23.637+0000] {standard_task_runner.py:57} INFO - Started process 21729 to run task
[2024-12-13T14:51:23.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mancity_to_postgres_etl', 'etl_erling_halaand_logs', 'manual__2024-12-13T14:51:21.223048+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/mancity_to_postgres_etl.py', '--cfg-path', '/tmp/tmpmsmcx0p4']
[2024-12-13T14:51:23.641+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask etl_erling_halaand_logs
[2024-12-13T14:51:23.692+0000] {task_command.py:410} INFO - Running <TaskInstance: mancity_to_postgres_etl.etl_erling_halaand_logs manual__2024-12-13T14:51:21.223048+00:00 [running]> on host 653f470dc9b4
[2024-12-13T14:51:23.886+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mancity_to_postgres_etl' AIRFLOW_CTX_TASK_ID='etl_erling_halaand_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T14:51:21.223048+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T14:51:21.223048+00:00'
[2024-12-13T14:51:24.438+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mancity_to_postgres_etl.py", line 61, in etl_file_to_postgres
    df.to_sql(table_name, engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1728, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1621, in prep_table
    table = SQLTable(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 805, in __init__
    self.table = self._create_table_setup()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1102, in _create_table_setup
    return Table(self.name, meta, *columns, schema=schema)
  File "<string>", line 2, in __new__
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 700, in _init
    self._init_items(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 144, in _init_items
    spwd(self, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 1047, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 1886, in _set_parent
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.
[2024-12-13T14:51:24.494+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=mancity_to_postgres_etl, task_id=etl_erling_halaand_logs, execution_date=20241213T145121, start_date=20241213T145123, end_date=20241213T145124
[2024-12-13T14:51:24.509+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 98 for task etl_erling_halaand_logs (Column must be constructed with a non-blank name or assign a non-blank .name before adding to a Table.; 21729)
[2024-12-13T14:51:24.518+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T14:51:24.569+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
