[2024-12-13T22:02:04.361+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_kyle_walker_logs manual__2024-12-13T22:00:52.675197+00:00 [queued]>
[2024-12-13T22:02:04.629+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_kyle_walker_logs manual__2024-12-13T22:00:52.675197+00:00 [queued]>
[2024-12-13T22:02:04.640+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-13T22:02:04.862+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transfer_kyle_walker_logs> on 2024-12-13 22:00:52.675197+00:00
[2024-12-13T22:02:05.006+0000] {standard_task_runner.py:57} INFO - Started process 68090 to run task
[2024-12-13T22:02:05.094+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_premierleague_to_analisis', 'transfer_kyle_walker_logs', 'manual__2024-12-13T22:00:52.675197+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/etl_premierleague_to_analisis.py', '--cfg-path', '/tmp/tmpvbgac_g2']
[2024-12-13T22:02:05.171+0000] {standard_task_runner.py:85} INFO - Job 280: Subtask transfer_kyle_walker_logs
[2024-12-13T22:02:06.114+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_premierleague_to_analisis.transfer_kyle_walker_logs manual__2024-12-13T22:00:52.675197+00:00 [running]> on host 653f470dc9b4
[2024-12-13T22:02:07.097+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_premierleague_to_analisis' AIRFLOW_CTX_TASK_ID='transfer_kyle_walker_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T22:00:52.675197+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T22:00:52.675197+00:00'
[2024-12-13T22:02:07.178+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T22:02:07.260+0000] {sql.py:375} INFO - Running statement: SELECT unnamed_0, header_performance, header_expected, header_sca, header_passes, header_carries, header_take_ons, date, dayofweek, comp, round, venue, result, team, opponent, game_started, position, minutes, goals, assists, pens_made, pens_att, shots, shots_on_target, cards_yellow, cards_red, touches, tackles, interceptions, blocks, xg, npxg, xg_assist, sca, gca, passes_completed, passes, passes_pct, progressive_passes, carries, progressive_carries, take_ons, take_ons_won, match_report FROM premierleague.public.kyle_walker_logs, parameters: None
[2024-12-13T22:02:07.276+0000] {sql.py:384} INFO - Rows affected: 65
[2024-12-13T22:02:07.339+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T22:02:07.543+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_premierleague_to_analisis.py", line 40, in transfer_table_in_same_connection
    db_hook.insert_rows(target_table, source_data, target_fields=columns, replace=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 465, in insert_rows
    sql = self._generate_insert_sql(table, values, target_fields, replace, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 299, in _generate_insert_sql
    raise ValueError("PostgreSQL ON CONFLICT upsert syntax requires an unique index")
ValueError: PostgreSQL ON CONFLICT upsert syntax requires an unique index
[2024-12-13T22:02:07.700+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=etl_premierleague_to_analisis, task_id=transfer_kyle_walker_logs, execution_date=20241213T220052, start_date=20241213T220204, end_date=20241213T220207
[2024-12-13T22:02:07.771+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 280 for task transfer_kyle_walker_logs (PostgreSQL ON CONFLICT upsert syntax requires an unique index; 68090)
[2024-12-13T22:02:07.810+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T22:02:07.950+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
