[2024-12-13T21:57:48.652+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_kai_havertz_logs manual__2024-12-13T21:56:42.352606+00:00 [queued]>
[2024-12-13T21:57:48.954+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_kai_havertz_logs manual__2024-12-13T21:56:42.352606+00:00 [queued]>
[2024-12-13T21:57:48.979+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-13T21:57:49.094+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transfer_kai_havertz_logs> on 2024-12-13 21:56:42.352606+00:00
[2024-12-13T21:57:49.140+0000] {standard_task_runner.py:57} INFO - Started process 66666 to run task
[2024-12-13T21:57:49.147+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_premierleague_to_analisis', 'transfer_kai_havertz_logs', 'manual__2024-12-13T21:56:42.352606+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/etl_premierleague_to_analisis.py', '--cfg-path', '/tmp/tmpjgzop76r']
[2024-12-13T21:57:49.157+0000] {standard_task_runner.py:85} INFO - Job 235: Subtask transfer_kai_havertz_logs
[2024-12-13T21:57:49.526+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_premierleague_to_analisis.transfer_kai_havertz_logs manual__2024-12-13T21:56:42.352606+00:00 [running]> on host 653f470dc9b4
[2024-12-13T21:57:51.457+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_premierleague_to_analisis' AIRFLOW_CTX_TASK_ID='transfer_kai_havertz_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T21:56:42.352606+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T21:56:42.352606+00:00'
[2024-12-13T21:57:51.743+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T21:57:51.965+0000] {sql.py:375} INFO - Running statement: SELECT match_id, player_id, minutes_played, goals, assists, shots, shots_on_target, tackles, interceptions, passes_completed, xg, xa FROM premierleague.public.kai_havertz_logs, parameters: None
[2024-12-13T21:57:52.018+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_premierleague_to_analisis.py", line 21, in transfer_table_in_same_connection
    source_data = db_hook.get_records(source_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "match_id" does not exist
LINE 1: SELECT match_id, player_id, minutes_played, goals, assists, ...
               ^

[2024-12-13T21:57:52.157+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=etl_premierleague_to_analisis, task_id=transfer_kai_havertz_logs, execution_date=20241213T215642, start_date=20241213T215748, end_date=20241213T215752
[2024-12-13T21:57:52.244+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 235 for task transfer_kai_havertz_logs (column "match_id" does not exist
LINE 1: SELECT match_id, player_id, minutes_played, goals, assists, ...
               ^
; 66666)
[2024-12-13T21:57:52.299+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T21:57:52.484+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
