[2024-12-13T21:57:36.049+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_mateo_kovacic_logs manual__2024-12-13T21:56:42.352606+00:00 [queued]>
[2024-12-13T21:57:36.480+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_mateo_kovacic_logs manual__2024-12-13T21:56:42.352606+00:00 [queued]>
[2024-12-13T21:57:36.564+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-13T21:57:37.229+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transfer_mateo_kovacic_logs> on 2024-12-13 21:56:42.352606+00:00
[2024-12-13T21:57:37.636+0000] {standard_task_runner.py:57} INFO - Started process 66652 to run task
[2024-12-13T21:57:37.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_premierleague_to_analisis', 'transfer_mateo_kovacic_logs', 'manual__2024-12-13T21:56:42.352606+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/etl_premierleague_to_analisis.py', '--cfg-path', '/tmp/tmpyw3jia_q']
[2024-12-13T21:57:37.771+0000] {standard_task_runner.py:85} INFO - Job 229: Subtask transfer_mateo_kovacic_logs
[2024-12-13T21:57:38.715+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_premierleague_to_analisis.transfer_mateo_kovacic_logs manual__2024-12-13T21:56:42.352606+00:00 [running]> on host 653f470dc9b4
[2024-12-13T21:57:42.922+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_premierleague_to_analisis' AIRFLOW_CTX_TASK_ID='transfer_mateo_kovacic_logs' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T21:56:42.352606+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T21:56:42.352606+00:00'
[2024-12-13T21:57:43.330+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T21:57:43.630+0000] {sql.py:375} INFO - Running statement: SELECT match_id, player_id, minutes_played, goals, assists, shots, shots_on_target, tackles, interceptions, passes_completed, xg, xa FROM premierleague.public.mateo_kovacic_logs, parameters: None
[2024-12-13T21:57:43.661+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_premierleague_to_analisis.py", line 21, in transfer_table_in_same_connection
    source_data = db_hook.get_records(source_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "match_id" does not exist
LINE 1: SELECT match_id, player_id, minutes_played, goals, assists, ...
               ^

[2024-12-13T21:57:44.079+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=etl_premierleague_to_analisis, task_id=transfer_mateo_kovacic_logs, execution_date=20241213T215642, start_date=20241213T215736, end_date=20241213T215744
[2024-12-13T21:57:44.370+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 229 for task transfer_mateo_kovacic_logs (column "match_id" does not exist
LINE 1: SELECT match_id, player_id, minutes_played, goals, assists, ...
               ^
; 66652)
[2024-12-13T21:57:44.518+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T21:57:45.392+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
