[2024-12-16T18:59:31.107+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-16T18:59:28.495042+00:00 [queued]>
[2024-12-16T18:59:31.113+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-16T18:59:28.495042+00:00 [queued]>
[2024-12-16T18:59:31.113+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-16T18:59:31.120+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): arsenal_etl_group.etl_arsenal_task> on 2024-12-16 18:59:28.495042+00:00
[2024-12-16T18:59:31.126+0000] {standard_task_runner.py:57} INFO - Started process 56879 to run task
[2024-12-16T18:59:31.128+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'arsenal_mancity_etl', 'arsenal_etl_group.etl_arsenal_task', 'manual__2024-12-16T18:59:28.495042+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/arsenal_mancity_etl.py', '--cfg-path', '/tmp/tmpijlztr84']
[2024-12-16T18:59:31.130+0000] {standard_task_runner.py:85} INFO - Job 307: Subtask arsenal_etl_group.etl_arsenal_task
[2024-12-16T18:59:31.189+0000] {task_command.py:410} INFO - Running <TaskInstance: arsenal_mancity_etl.arsenal_etl_group.etl_arsenal_task manual__2024-12-16T18:59:28.495042+00:00 [running]> on host 653f470dc9b4
[2024-12-16T18:59:31.255+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='arsenal_mancity_etl' AIRFLOW_CTX_TASK_ID='arsenal_etl_group.etl_arsenal_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T18:59:28.495042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T18:59:28.495042+00:00'
[2024-12-16T18:59:31.567+0000] {logging_mixin.py:149} INFO - Processing file: ben_white_match_logs_2023_2024.json
[2024-12-16T18:59:31.567+0000] {logging_mixin.py:149} INFO - Columns in DataFrame: ['', 'header_performance', 'header_expected', 'header_sca', 'header_passes', 'header_carries', 'header_take_ons', 'date', 'dayofweek', 'comp', 'round', 'venue', 'result', 'team', 'opponent', 'game_started', 'position', 'minutes', 'goals', 'assists', 'pens_made', 'pens_att', 'shots', 'shots_on_target', 'cards_yellow', 'cards_red', 'touches', 'tackles', 'interceptions', 'blocks', 'xg', 'npxg', 'xg_assist', 'sca', 'gca', 'passes_completed', 'passes', 'passes_pct', 'progressive_passes', 'carries', 'progressive_carries', 'take_ons', 'take_ons_won', 'match_report']
[2024-12-16T18:59:31.568+0000] {logging_mixin.py:149} INFO - Error processing file ben_white_match_logs_2023_2024.json: "Missing columns in DataFrame: ['match_id', 'goals_scored', 'goals_conceded']"
[2024-12-16T18:59:31.568+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/arsenal_mancity_etl.py", line 83, in etl_arsenal
    pd.concat(all_matches).drop_duplicates().to_sql('matches', engine, if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
[2024-12-16T18:59:31.580+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=arsenal_mancity_etl, task_id=arsenal_etl_group.etl_arsenal_task, execution_date=20241216T185928, start_date=20241216T185931, end_date=20241216T185931
[2024-12-16T18:59:31.589+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 307 for task arsenal_etl_group.etl_arsenal_task (No objects to concatenate; 56879)
[2024-12-16T18:59:31.597+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-16T18:59:31.632+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
