[2024-12-13T21:37:52.912+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_goalkeeperstats manual__2024-12-13T21:37:51.104851+00:00 [queued]>
[2024-12-13T21:37:52.937+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_premierleague_to_analisis.transfer_goalkeeperstats manual__2024-12-13T21:37:51.104851+00:00 [queued]>
[2024-12-13T21:37:52.938+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-13T21:37:52.966+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transfer_goalkeeperstats> on 2024-12-13 21:37:51.104851+00:00
[2024-12-13T21:37:52.972+0000] {standard_task_runner.py:57} INFO - Started process 59284 to run task
[2024-12-13T21:37:52.975+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_premierleague_to_analisis', 'transfer_goalkeeperstats', 'manual__2024-12-13T21:37:51.104851+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/etl_premierleague_to_analisis.py', '--cfg-path', '/tmp/tmpqz4wfq4x']
[2024-12-13T21:37:52.986+0000] {standard_task_runner.py:85} INFO - Job 187: Subtask transfer_goalkeeperstats
[2024-12-13T21:37:53.146+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_premierleague_to_analisis.transfer_goalkeeperstats manual__2024-12-13T21:37:51.104851+00:00 [running]> on host 653f470dc9b4
[2024-12-13T21:37:53.444+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_premierleague_to_analisis' AIRFLOW_CTX_TASK_ID='transfer_goalkeeperstats' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T21:37:51.104851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T21:37:51.104851+00:00'
[2024-12-13T21:37:53.491+0000] {base.py:73} INFO - Using connection ID 'shared_postgres' for task execution.
[2024-12-13T21:37:53.508+0000] {sql.py:375} INFO - Running statement: SELECT gk_stat_id, match_id, player_id, shots_on_target_against, goals_against, saves, save_percentage, clean_sheets, psxg, passes_completed_launched, passes_launched, passes_pct_launched, goal_kicks, crosses_faced, crosses_stopped, crosses_stopped_pct, def_actions_outside_pen_area, avg_distance_def_actions FROM premierleague.public.goalkeeper_stats_source, parameters: None
[2024-12-13T21:37:53.518+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_premierleague_to_analisis.py", line 22, in transfer_table_in_same_connection
    source_data = db_hook.get_records(source_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 235, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "public.goalkeeper_stats_source" does not exist
LINE 1: ...s_outside_pen_area, avg_distance_def_actions FROM premierlea...
                                                             ^

[2024-12-13T21:37:53.563+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_premierleague_to_analisis, task_id=transfer_goalkeeperstats, execution_date=20241213T213751, start_date=20241213T213752, end_date=20241213T213753
[2024-12-13T21:37:53.593+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 187 for task transfer_goalkeeperstats (relation "public.goalkeeper_stats_source" does not exist
LINE 1: ...s_outside_pen_area, avg_distance_def_actions FROM premierlea...
                                                             ^
; 59284)
[2024-12-13T21:37:53.622+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T21:37:53.718+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
